apiVersion: 1
# Par YAML :
# - https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/
# - https://github.com/grafana/grafana/blob/main/conf/provisioning/alerting/sample.yaml
# Par API :
# - https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#validation-error
groups:
  - orgId: 1
    name: Managed
    folder: GET
    interval: 60s
    rules:
    - uid: More_than_1_call_per_minute
      title: More than 1 call per minute
      condition: C
      data:
      - refId: A
        datasourceUid: mimir
        relativeTimeRange:
          from: 300
          to: 0
        model:
          datasource:
            type: prometheus
            uid: 'mimir'
          expr: 'rate(fastapi_requests_total{method="GET"}[1m]) > 0'
          hide: false
          intervalMs: 1000
          legendFormat: '__auto'
          maxDataPoints: 43200
          range: true
          refId: A
      - refId: B
        datasourceUid: "__expr__"
        relativeTimeRange:
          from: 300
          to: 0
        model:
          conditions:
          - evaluator:
              params: []
              type: gt
            operator:
              type: and
            query:
              params:
              - A
            reducer:
              type: last
            type: query
          datasource:
            type: __expr__
            uid: '__expr__'
          expression: A
          intervalMs: 1000
          maxDataPoints: 43200
          refId: B
          type: reduce
          reducer: mean
      - refId: C
        datasourceUid: "__expr__"
        relativeTimeRange:
          from: 300
          to: 0
        model:
          conditions:
          - evaluator:
              params:
              - 0
              type: gt
            operator:
              type: and
            query:
              params:
              - C
            reducer:
              type: last
            type: query
          datasource:
            type: __expr__
            uid: '__expr__'
          expression: B
          intervalMs: 1000
          maxDataPoints: 43200
          refId: C
          type: threshold
      noDataState: NoData
      executionErrorState: Error
      for: 5m
      annotations:
        description: "Receive more than 1 call per minute on GET method"
        summary: "This alert is just a demonstration on how to add alert and notification"
        runbook_url: ""
      labels:
        Creator: TDE
        severity: INFO

contactPoints:
  - orgId: 1
    name: Slack
    receivers:
    - uid: Slack
      type: slack
      settings:
        mentionChannel: here
        mentionUsers: XXXXXXX
        url: https://hooks.slack.com/services/XXXXX/YYYYY/ZZZZZZZZ
        username: Grafana Test Auto Alert

policies:
  - orgId: 1
    receiver: Slack
    group_by:
    - grafana_folder
    - alertname
    routes:
